### ISSUE TITLE
How I can implement the feedback feature

### ISSUE THREAD

**Issue by darthzyklus** [LaraBug/LaraBug#40]
Hi folks, nice work on this incredible app.

I need some guidance on how to implement the feedback feature on my Laravel app. I couldn't find any docs about it.

I will really appreciate the help. 

Have a great day!

**Comment by Cannonb4ll** [comment]
Hey!

We've had it available back in the day when it was paid. We're now refactoring some stuff to make it more fluent and easier to implement. We'll be releasing this very soon including the docs.

**Comment by darthzyklus** [comment]
@Cannonb4ll That would be great. Thank you very much!

**Comment by renamate** [comment]
It would be great if they could have this feature working.

Thank you very much for the development of this app.

**Comment by dgillier** [comment]
Any news on the feedback feature ?

thanks, Denis
