### ISSUE TITLE
Relative Path in JavaScript Exception Report Route

### ISSUE THREAD

**Issue by EvilLooney** [LaraBug/LaraBug#43]
Hi, 

This line's use of window.location should instead use window.location.origin I believe:
https://github.com/LaraBug/LaraBug/blob/ad1d3a4f6994c3a5d7a70fe095630f18189a7fe2/resources/views/larabug-js-client.blade.php#L30

If not, it will try to connect to a route point relative to the correct request.
Ex: https://mysite.test/some/path/larabug-api/javascript-report

Cheers!

**Comment by Cannonb4ll** [comment]
Hi!

Thank you, will issue a fix!

**Comment by GavG** [comment]
Hi I'm not sure the above fix (https://github.com/LaraBug/LaraBug/commit/c064d6fbf8823655e24b58cc5d468ad26fc70398) resolved this issue, 

The applied fix was to the error report payload Url but the report is still being sent to:

`window.location + '/larabug-api/javascript-report'`

See L30:

https://github.com/LaraBug/LaraBug/blob/c064d6fbf8823655e24b58cc5d468ad26fc70398/resources/views/larabug-js-client.blade.php#L30

**Comment by mike-taylorprops** [comment]
I'm still seeing the issue. Using this instead
window.location.protocol+'//'+window.location.hostname + '/larabug-api/javascript-report

**Comment by sinnbeck** [comment]
I don't think the fix has been released yet?

https://github.com/LaraBug/LaraBug/releases
