### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by lloricode** [LaraBug/LaraBug#59]
Hi!, it is good idea to add collaborators here in future? like project can share to other larabug users?

Thank you

**Comment by Cannonb4ll** [comment]
Hi,

Yes, this is certainly something we'd like to see. But this is more something for https://github.com/LaraBug/larabug-app instead of this repository.

**Comment by lloricode** [comment]
> Hi,
> 
> Yes, this is certainly something we'd like to see. But this is more something for https://github.com/LaraBug/larabug-app instead of this repository.

thanks this is very helpful
