### ISSUE TITLE
It's not installing in Laravel 9

### ISSUE THREAD

**Issue by Fardeen-sumatoglobal** [LaraBug/LaraBug#68]
![Screenshot 2022-02-09 at 1 19 04 PM](https://user-images.githubusercontent.com/58284604/153146372-66d1234c-d9dd-4cdd-b2c5-5427945c3bc6.png)

**Comment by Cannonb4ll** [comment]
Can you update to version 2.5 and try again?

**Comment by Fardeen-sumatoglobal** [comment]
> Can you update to version 2.5 and try again?
Thanks its working now
