### ISSUE TITLE
Support LogManager to log Exceptions to LaraBug

### ISSUE THREAD

**Issue by nickurt** [LaraBug/LaraBug#7]
Laravel 5.6 [introduced](https://laravel.com/docs/5.6/upgrade#upgrade-5.6.0) support for `improved` [logging](https://laravel.com/docs/6.x/logging) via `config/logging.php`, is it possible to create a custom LaraBug-driver to use this, instead of using the `app/Exceptions/Handler.php`-way?

E.g. by other error reporting tools for Laravel ..

Flare - https://flareapp.io/docs/general/projects
Bugsnag - https://docs.bugsnag.com/platforms/php/laravel/#reporting-unhandled-exceptions
Sentry - https://docs.sentry.io/platforms/php/laravel/#using-laravel-56-log-channels
Rollbar - https://docs.rollbar.com/docs/laravel

**Comment by Cannonb4ll** [comment]
Good idea, I will take a look at this, might smoothen out the installation process 🚀
