### ISSUE TITLE
email notification is not working

### ISSUE THREAD

**Issue by hr-mat** [LaraBug/LaraBug#80]
Hey, 
currently trying to integrate this to my laravel project. Exceptions are correctly added to the dashboard but i am not receiving any email notification.  Already tried turning on and off  the "receive email notificatin" settings for the project, but its not changing anything. 
DId i miss some steps?

**Comment by Cannonb4ll** [comment]
It's not you, we've recently disabled emailing as it became too expensive to keep it going, we'll be doing some clustering of the emails better soon.
