### ISSUE TITLE
error when trying to mark as fixed

### ISSUE THREAD

**Issue by azrirsml** [LaraBug/LaraBug#92]
![image](https://github.com/LaraBug/LaraBug/assets/28720643/b26d8955-8a9f-4543-8a68-8ca78cff608d)

**Comment by pemudakoding** [comment]
https://github.com/LaraBug/larabug-app/pull/118

**Comment by pemudakoding** [comment]
Hi @Cannonb4ll this issue might need to update to be closed since the merge request already merged
