### ISSUE TITLE
Site is down since the 10 dec?

### ISSUE THREAD

**Issue by dgillier** [LaraBug/LaraBug#94]
![Screenshot 2023-12-11 at 10 53 26](https://github.com/LaraBug/LaraBug/assets/37960204/26d1ecd7-aa5c-47d7-839d-98a0c111343f)

**Comment by Glennmen** [comment]
Sorry about that, @Cannonb4ll is aware of the issue and working on it.
Feel free to join the LaraBug discord for latest updates: https://discord.gg/uFADYygT2D

**Comment by Cannonb4ll** [comment]
Fixed!
